### ISSUE TITLE
vim-endwise support

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/vim-teal#2]
It would be nice to add support for [vim-endwise](https://github.com/tpope/vim-endwise). Maybe we could create a `plugin/teal.vim` file with the following content (or something similar):
```vim
autocmd FileType teal
    \ let b:endwise_addition = 'end' |
    \ let b:endwise_words = 'function,do,then,record,enum' |
    \ let b:endwise_pattern = '^\s*\zs\%(\%(local\s\+\)\=function\)\>\%(.*\<end\>\)\@!\|\<\%(then\|do\|record\|enum\)\ze\s*$' |
    \ let b:endwise_syngroups = '???' " I'm not sure about the syntax's group names anymore
```

**Comment by 3uclidian** [comment]
This should be pretty simple. I've attempted to keep the groups consistently named so the relevant groups should all be of the format `teal(.*)Block`. But I'd have to make sure.

They should all be listed in the `tealStatement` cluster though.
