### ISSUE TITLE
Specific colorscheme support?

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/vim-teal#6]
I personally use the Dracula colorscheme which has a [specification](https://spec.draculatheme.com/) for how certain things like type annotations should be colored and the default highlight groups can't support it.
Maybe this could be supported with a ftplugin?
```viml
if g:colors_name == "dracula"
	hi! link tealSelf DraculaPurpleItalic
	" etc ...
endif
```

Or should this be done by the colorscheme itself? As I know dracula definitely has filetype plugins to set colors.
I feel as though this sort of thing should be maintained here since the highlight groups may change subtly in the future and it could be a hassle to pull request a bunch of colorscheme repos.

I'm currently just doing this in my init.vim which feels wrong.

**Comment by euclidianAce** [comment]
@pdesaulniers Any opinions on this? I think once #9 gets merged I'll add a section for this in `plugin/teal.vim`

**Comment by pdesaulniers** [comment]
I think you can throw this into `plugin/teal.vim` for the time being. Ideally, this should be contributed to the theme itself once vim-teal is mature enough.
